trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'npm install'
  - script: |
      npm run release
    env:
      GIT_CREDENTIALS: $(System.AccessToken)
    displayName: "Bump release version"
