name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

  deploy-to-dev:
    needs: publish
    runs-on: ubuntu-latest
    environment: tagging-test-DEV
    steps:
      - uses: actions/download-artifact@v4
      - name: Deploy to Dev Environment
        run: echo "Deploying to Dev environment..."
        # Add your deployment script/command here

  deploy-to-uat:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    environment: tagging-test-UAT
    steps:
      - uses: actions/download-artifact@v4
      - name: Deploy to UAT Environment
        run: echo "Deploying to UAT environment..."
        # Add your deployment script/command here

  deploy-to-prod:
    needs: deploy-to-uat
    runs-on: ubuntu-latest
    environment: tagging-test-PROD
    steps:
      - uses: actions/download-artifact@v4
      - name: Deploy to Production Environment
        run: echo "Deploying to Production environment..."
        # Add your deployment script/command here